filebeat.modules:
- module: system
  syslog:
    enabled: true
  auth:
    enabled: true

#========================== Elasticsearch output ===============================
output.elasticsearch:
  # hosts: ["${ELASTICSEARCH_HOST}:9200"]
  # username: ${ELASTICSEARCH_USERNAME}
  # password: ${ELASTICSEARCH_PASSWORD}
  hosts: ["https://localhost:9200"]
  username: "elastic"
  password: "tjIoOpgxENxjd-N1tAIW"

# #============================== Dashboards =====================================
# setup.dashboards:
#   enabled: true

# #============================== Kibana =========================================
# setup.kibana:
#   host: "${KIBANA_HOST}:80"
#   username: ${ELASTICSEARCH_USERNAME}
#   password: ${ELASTICSEARCH_PASSWORD}

# #============================== Xpack Monitoring ===============================
# xpack.monitoring:
#   enabled: true
#   elasticsearch:


# output.kafka:
#   # initial brokers for reading cluster metadata
#   hosts: ["localhost:9092"]
#   # message topic selection + partitioning
#   topic: 'percobaan_pesan'
#   partition.round_robin:
#     reachable_only: false
#   required_acks: 1
#   compression: gzip
#   max_message_bytes: 1000000



# output.file:
#   path: "/usr/share/filebeat/outputlog/outputlog"

# setup.kibana:
#   host: http://localhost:5601
#   username: elastic
#   password: tjIoOpgxENxjd-N1tAIW

# processors:
#   - add_docker_metadata:
#       host: "unix:///host_docker/docker.sock"

# filebeat.prospectors:
# - type: log
#   enabled: true
#   paths:
#     - /usr/share/filebeat/mylog/*.log

# setup.template.name: "filebeat-"
# setup.template.pattern: "filebeat-*"
# setup.dashboards.enabled: true

# setup.kibana:
#   host: https://localhost:5601
#   username: elastic
#   password: tjIoOpgxENxjd-N1tAIW

# output.elasticsearch:
#   hosts: ["http://localhost:9200"]
#   username: elastic
#   password: tjIoOpgxENxjd-N1tAIW
#   index: "filebeat-%{+yyyy.MM.dd}"